services:
  app:
    image: docker-spring-boot-postgres:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - psql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/greyson

  psql-db:
    image: "postgres"
    container_name: "psql-db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greyson
    ports:
      - "5432:5432"
volumes:
  postgres-data: